# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15u57Qd4OxV9Kihe3jqmLXlxxWGpjM60p
"""

mes = [['Январь', 31], ['Февраль', 28], ['Март', 31], ["Апрель", 30], ["Май", 31], ["Июнь", 30], ["Июль", 31], ["Август", 31], ["Сентябрь", 30], ["Октябрь", 31], ['Ноябрь', 30], ['Декабрь',31]]
m = int(input("Введите номер месяца:"))

if int(m) <= 0 or int(m) > 12:

 print("Вы ввели неверный месяц")
 m = int(input("Введите номер месяца:"))
 a = (mes[m-1][0])
 b = (mes[m-1][1])

 print ("Вы ввели",a , b,"дней")
 
else:
#try: 
 a, b = 0, 0 
 a = (mes[m-1][0])
 b = (mes[m-1][1])

 print ("Вы ввели",a , b,"дней")